PowerDNS/pdns_recursor-ansible

README.md, defaults/main.yml, molecule.yml, playbook.yml, tasks/inspect-Debian.yml, tasks/inspect-RedHat.yml, tasks/main.yml, vars/Debian.yml, vars/main.yml
This PR aims to fix issue #23 and improve the way we handle the setup of customer PowerDNS Recursor repositories.
An alternative fix for issue #23 would be adding `ignore_errors: True` to the `include_vars` task.
=> Fixing issue #23 and hardening the repo installation tasks

tasks/install-pdns.yml, tasks/main.yml
Copied from https://github.com/PowerDNS/pdns-ansible/commit/09585360b1eca1f3fd34e41114ca76d5bcf341c5 since it's also needed for recursor.
Additional string mangling because pdns_rec_package_version appears to contain a new line (and apt chokes on that). A fix in atosatto.packages-extras (sanitize the version string over there) might be better, this is a quick workaround.
=> Handle different version string for Debian and CentOS

templates/recursor.conf.j2
`threads` variable works well when set to the number of vcpus on a system.  However, if using a small/test system, this might be "1".  With the existing template, this sets `threads` to `yes` instead of `1`, and pdns-recursor won't start.
With the change, `threads` is set to the string of whatever the variable is set to, and other variabes are handled in the same manner as before.
There are other ways to accomplish this, but it is the only case  I know of with the pdns-recursor role, so this is an easy fix and might not need to be more complicated.
=> add special case for "threads" variable

README.md, defaults/main.yml, handlers/main.yml, molecule/pdns-rec-41/molecule.yml, molecule/pdns-rec-master/molecule.yml, molecule/resources/create.yml, tasks/configure.yml, tasks/install.yml, tasks/main.yml
This PR introduces to new variables `pdns_rec_service_state` and `pdns_rec_service_enabled` to configure the status of the PowerDNS Recursor service.
A typical use-case is the installation of the PowerDNS Recursor without actually starting the service automatically via Ansible.
=> Add some variables to allow to configure the status of the Recursor service

.travis.yml, tox.ini
This PR updates the test-suite to test against more recent versions of Ansible.
=> Update the molecule test-suite to test against Ansible 2.5, 2.6 and 2.7

molecule/resources/tests/all/test_common.py, tasks/configure.yml
Do not touch right for powerdns config and leave it as in package. Because of 750 (default is 755) I unable to place additional configuration files in config directory.
=>  Disable rights change for pdns config dir

templates/recursor.conf.j2
sameas() in jinja2 is more narrow, preventing "truthy" and "falsy" values from being misinterpreted.
=> Stop interpreting 0 & 1 as no & yes

tasks/configure.yml
As per the title, this PR ensures that the Recursor is restarted on changes to the systemd unit overrides.
=> Make sure to restart the Recursor on systemd-unit changes

.gitignore, .travis.yml, README.md, molecule/pdns-rec-42/molecule.yml, molecule/pdns-rec-42/playbook.yml, molecule/pdns-rec-master/molecule.yml, molecule/pdns-rec-master/playbook.yml, molecule/resources/Dockerfile.centos-systemd.j2, molecule/resources/create.yml, molecule/resources/host_vars/centos-8.yml, molecule/resources/prepare.yml, molecule/resources/tests/all/test_common.py, molecule/resources/tests/repo-42/test_repo_42.py, molecule/resources/tests/repo-master/test_repo_master.py, molecule/resources/vars/pdns-rec-repo-41.yml, molecule/resources/vars/pdns-rec-repo-42.yml, tasks/repo-RedHat.yml, tox.ini
This PR implements multiple enhancements to the versions of the software used by the Travis CI infrastructure:
- add Python 3 to the tests matrix
- add Ansible 2.8 and Ansible 2.9 to the tests matrix
- remove Ansible 2.5 and Ansible 2.6 from the tests matrix (as these are unmaintained and eol)
- ~add CentOS 8 as test target~
- update the testinfra code to test against the 4.2.0 release of the PowerDNS Recursor
- speedup the tests execution enabling Ansible cache and pipelining
=> Update the CI to test against more recent Ansible/Python/OS versions 

vars/main.yml
If RHEL is used, yum will fail when repo url is not https:
```
http://repo.powerdns.com/centos/x86_64/7Server/rec-43/repodata/repomd.xml: [Errno 14] HTTP Error 403 - Forbidden
Trying other mirror.
```
=> Use https repo url on CentOS/RHEL repos

README.md, defaults/main.yml, molecule/pdns-rec-42/molecule.yml
Make sure to configure the User and Group in systemd to install correctly the Recursor 4.3
=> Fix the default pdns_rec_service_overrides to work with the Recursor 4.3.x

tasks/repo-Debian.yml, vars/main.yml
Switch to HTTPS for the PowerDNS repositories configuration.
=> Use HTTPs everywhere to connect to the PowerDNS repositories

vars/main.yml
just what is says on the subject
Successfully tested for pdns_rec_powerdns_repo_47 on Ubuntu 20.04.4 LTS.
=> added 4.6.x and 4.7.x release train repositories

README.md
I fixed some indentation problems. With current the recursor.conf is populated with pdns_rec_service_overrides=xxx which is wrong
=> Fix indentation for pdns_rec_service_overrides.

tasks/main.yml
This will fix the Deprecation warning: "ansible.builtin.include has been removed"
Currently Ansible runs are breaking with:
```ERROR! [DEPRECATED]: ansible.builtin.include has been removed. Use include_tasks or import_tasks instead. This feature was removed from ansible-core in a release after 2023-05-16. Please update your playbooks.```
=> Replace the deprecated include with include_task

.github/workflows/main.yml, molecule/pdns-rec-48/molecule.yml, molecule/pdns-rec-49/molecule.yml, molecule/pdns-rec-50/molecule.yml, molecule/pdns-rec-master/molecule.yml, molecule/resources/Dockerfile.centos-systemd.j2, molecule/resources/tests/all/test_common.py, molecule/resources/tests/repo-48/test_repo_48.py, molecule/resources/tests/repo-49/test_repo_49.py, molecule/resources/tests/repo-50/test_repo_50.py, molecule/resources/tests/repo-master/test_repo_master.py, tasks/repo-RedHat.yml
Added OL9, Rocky, and AlmaLinux 8 and 9 as CI targets.
Test `main` workflow weekly and make it not stop on failure so the remaining distros are tested.
=> Add OL9, Rocky and AlmaLinux 8 and 9 as CI targets

molecule/pdns-rec-48/molecule.yml, molecule/pdns-rec-49/molecule.yml, molecule/pdns-rec-50/molecule.yml, molecule/pdns-rec-master/molecule.yml, molecule/resources/create.yml, molecule/resources/tests/repo-master/test_repo_master.py, molecule/resources/vars/pdns-rec-common.yml, molecule/resources/vars/pdns-rec-repo-47.yml, molecule/resources/vars/pdns-rec-repo-48.yml, molecule/resources/vars/pdns-rec-repo-49.yml, molecule/resources/vars/pdns-rec-repo-50.yml, molecule/resources/vars/pdns-rec-repo-master.yml, templates/override-service.systemd.conf.j2, test-requirements.txt
Included in this PR are fixes for:
- Version of `docker-py` set to 7.1.0. Older versions require a specific version of `requests` to work (see [here](https://github.com/docker/docker-py/issues/3256)
- Move from tests from`centos:7` to `oraclelinux:7`
- Adapt tests to comply with newer versions of rec that get the output of `/usr/sbin/pdns_recursor --version` through stdout instead of stderr.
- Mount `/sys/fs/cgroups` as `rw` to overcome the error that made containers fail after starting: `Failed to create /actions_job/b23bdd0759a907717ae61975e6bf5b5044ae8f9dee961e93a4c108e30868f395/init.scope control group: Read-only file system`
=> GH Actions: fix issues with CI

meta/main.yml, molecule/pdns-rec-48/molecule.yml, molecule/pdns-rec-49/molecule.yml, molecule/pdns-rec-50/molecule.yml, molecule/pdns-rec-master/molecule.yml
Fixes errors in CI.
Platforms removed:
- `oraclelinux-7`
- `debian-10`
=> Removed EOL targets RHEL-7 and Debian-10

tasks/configure.yml
systemd said: "This has no effect as configuration data is accessible via APIs without restrictions."
=> Small file permission fix

.ansible-lint, .github/workflows/main.yml, .yamllint, molecule/pdns-rec-48/converge.yml, molecule/pdns-rec-49/converge.yml, molecule/pdns-rec-50/converge.yml, molecule/pdns-rec-51/converge.yml, molecule/pdns-rec-master/converge.yml, molecule/pdns-rec-master/molecule.yml, molecule/resources/create.yml, molecule/resources/destroy.yml, molecule/resources/prepare.yml, molecule/resources/tests/all/test_common.py, test-requirements.txt, tox.ini
Tests now run against `ansible-core 2.14, 2.15 and 2.16`.
Added linter to CI workflow and fixed some lint issues
=> CI tests: upgraded version of molecule and ansible-core packages

tasks/configure.yml
The legacy configuration format is difficult to test with the template.validate attribute. This is the next best thing. Right before restart, we run --config=check. If it fails, the play stops. Avoids putting the service in a boot-loop.
Skipped during check-mode, because we want to always check the new configuration, never the previous one.
Something to consider when engineering the new configuration format.
=> Test configuration before restarting
